<?php
header("Access-Control-Allow-Origin: *"); // Allow all origins (for development)
header("Content-Type: application/json");

$accessToken = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIyNmY4MTNiZWVkODcyMGU5MjI4NTMzYTA2Y2U0MTE2MiIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6NzcwYWU0ZmUtMGJhOS00YmQ2LWIwYTctYTNlNmE4ZjZhZDAyIl19LHsiaWQiOiJtZXRhYXBpLXJlc3QtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDo3NzBhZTRmZS0wYmE5LTRiZDYtYjBhNy1hM2U2YThmNmFkMDIiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOjc3MGFlNGZlLTBiYTktNGJkNi1iMGE3LWEzZTZhOGY2YWQwMiJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOjc3MGFlNGZlLTBiYTktNGJkNi1iMGE3LWEzZTZhOGY2YWQwMiJdfSx7ImlkIjoibWV0YXN0YXRzLWFwaSIsIm1ldGhvZHMiOlsibWV0YXN0YXRzLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDo3NzBhZTRmZS0wYmE5LTRiZDYtYjBhNy1hM2U2YThmNmFkMDIiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6NzcwYWU0ZmUtMGJhOS00YmQ2LWIwYTctYTNlNmE4ZjZhZDAyIl19XSwiaWdub3JlUmF0ZUxpbWl0cyI6ZmFsc2UsInRva2VuSWQiOiIyMDIxMDIxMyIsImltcGVyc29uYXRlZCI6ZmFsc2UsInJlYWxVc2VySWQiOiIyNmY4MTNiZWVkODcyMGU5MjI4NTMzYTA2Y2U0MTE2MiIsImlhdCI6MTczNDE5MzY1NCwiZXhwIjoxNzQxOTY5NjU0fQ.KhYazpUV8xaMdUCwpaqIcrJjF0tHLb6xqWIL5zhQ7SWzqC5OhwJIgND-JMKVy8pXhvPgfZ_pAUwhuDwSXZ_cChbJFmOyZ-PTPEA9NbMESUw_A4hbiJIki1qvy4YWuY3PwR-E-14CGy4wSVT6qAZxca82Ywd_EbDnHoeThYQ7JnvMHNKh1yuVEi9okQhZZikmF0uqmWT2XMK69U_VosRdLxW-Z4Eq9jTJTbGDnfqiNWC_pw3dg8iIcJpx8IR46rJV6eYqLOAu1cXix5fqb2v88SRI45KXF5Pjdkxpibor68d5JH0pqB0xbI4UNzII9Zoey69vKjQDzFfqpEFXAgQ--VJ4sYoRMxRI1ubv3a2mpM1NTllvoFchOsoxGi3tSAxPH53FeXToY9sRJJ5uKJwp7KibI-SaPjSxqf-H10YrxwTVg4aYvXvb9mQDlZjaHTkoJ6lWESXEK7MfRmerYSWAUCUOXL_6POqDDZYGLeIaLvxZSc1SMoC08sXPeJD5x2jQbbRJDnE2u45bBKOz_nlukJ6Yczma1rgTYRPA8mAwYyWiYMsmIbvjwV7V90p8TZIG-6hiwD5xrm3voqLlbBUib0aoEhpWZg1mD46A8fFr0oRQqjkRzI19TM9jPR7JVMUzvlumHIxpUJwTAULPUlGfWfK_odWZCZyDxOf0g4k8dRE";
$url = "https://api.metaapi.cloud/v1/accounts/$accountId/symbols/EURUSD/price";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    "Authorization: Bearer $accessToken",
    "Content-Type: application/json"
]);

// Ignore SSL validation (for development only)
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

$response = curl_exec($ch);
if (curl_errno($ch)) {
    http_response_code(500);
    echo json_encode(["error" => curl_error($ch)]);
} else {
    echo $response;
}
curl_close($ch);
?>